version: '3'

services:
    nginx:
        container_name: nginx
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        env_file: ./.env
        ports:
            - "443:443"
        restart: on-failure

