version: '3'

services:
    nginx:
        build: ./requirements/nginx/
        restart: always
        ports: 
            - "443:443"
        container_name: nginx
        network:
            - Inception
    wordpress:
        build: ./requirements/wordpress/
        restart: always
        ports:
            - "9000:9000"
        environment:
            WORDPRESS_DOMAIN: ${DOMAIN_NAME}
        container_name: wordpress
        network:
            - Inception
networks:
    Inception:
        driver: bridge 